mybatis:
  typeAliasesPackage: com.codeZ.boot.domain
  mapperLocations: classpath:mapping/*.xml
mapper:
  mappers:
  - com.codeZ.boot.util.MyMapper
  not-empty: false
  identity: MYSQL
pagehelper:
  auto-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql
spring:
  thymeleaf:
    cache: false
  resources:
    static-locations:
    - classpath:/myStatic/
    
#mybatis
#mybatis.type-aliases-package=com.lf.entity
#mybatis.mapper-locations=classpath:mapper/*.xml
#mappers 多个接口时逗号隔开
#mapper.mappers=tk.mybatis.mapper.common.Mapper
#mapper.mappers=com.lf.util.MyMapper
#mapper.not-empty=false
#mapper.identity=MYSQL
#pagehelper
#pagehelper.helperDialect=mysql
#pagehelper.reasonable=true
#pagehelper.supportMethodsArguments=true
#pagehelper.params=count=countSql
